From postgres


MAINTAINER Madhu-Dharmapuri

USER root

RUN export LANGUAGE=en_US.UTF-8

ADD config/hive-schema-2.3.0.postgres.sql /hive/hive-schema-2.3.0.postgres.sql
ADD config/hive-txn-schema-2.3.0.postgres.sql /hive/hive-txn-schema-2.3.0.postgres.sql

COPY config/init-hive-db.sh /docker-entrypoint-initdb.d/init-user-db.sh
