From gethue/hue:latest

MAINTAINER Madhu-Dharmapuri

USER root

ADD config/hue.ini /usr/share/hue/desktop/conf/hue.ini
ADD config/hue.ini /usr/share/hue/desktop/conf/hue-overrides.ini 
ADD config/hue.ini /usr/share/hue/tools/docker/hue/conf/hue-overrides.ini
RUN mkdir -p /etc/hive/conf

# set environment variables
ENV HIVE_CONF_DIR /etc/hive/conf

ADD config/hive-site.xml $HIVE_CONF_DIR/hive-site.xml
